
name: PR Gate

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 5 * * 1,4'

jobs:
  build-slothpu:
    defaults:
      run:
        shell: bash
        working-directory: emulator
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: pip install .
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=slothpu --cov-report=xml test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./emulator/coverage.xml # Appears to ignore working-directory
          flags: unittests
          name: codecov-umbrella
          verbose: true

  linting-flake8:
    defaults:
      run:
        shell: bash
        working-directory: emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: flake8 .

  linting-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable